### ISSUE TITLE
Issue when using SQLite with Android 7.0

### ISSUE THREAD

**Issue by anubhavranjan** [nishanil/Dev-Days-HOL#22]
An issue is seen to be appearing when using the NuGet package Microsoft.WindowsAzure.Mobile.SQLiteStore 2.1.0 in Android 7.0

The error appears with the following message:
`Detected problems with app native libraries(please consult log for details): libmonosgen-64bit-2.0.so: unauthorized access to "/system/lib64/libsqlite.so`

**Comment by nishanil** [comment]
Closed as part of  fix #23
