### ISSUE TITLE
Add "False build error reported by Intellisense that can be ignored" to ReadMe

### ISSUE THREAD

**Issue by sreerajPR** [nishanil/Dev-Days-HOL#8]
While building the solution or the PCL project, Visual Studio might raise a build error 

> The name 'InitializeComponent' does not exist in the current context
> Build action 'EmbeddedResource' is not supported by one or more of the project's targets.

This can be ignored and the project can be deployed. 

Above information can be added to the [ReadMe file](https://github.com/nishanil/Dev-Days-HOL/blob/master/01%20Dev-Labs/ReadMe.md) in first project to avoid confusions and save time.

**Comment by nishanil** [comment]
These are VS cache issues specific to user systems. It's not a good idea to add it to readme.
